sudo: false

language: node_js

node_js:
  - '8'

script:
  - "npm run build"

notifications:
  slack:
    secure: x1YX7LRJto8Sj3C0pO9NBx9OGxyPiL9pF18z9GOdrbF+73zsCyuTLPDsM1SI7ItaTzrhEqZdSXzQ7gy6MUJWF5rNAG8sE9bu8SCT1ev1KrJcmO0wCo4vCfVa+9wG5AuIcfdyJ2vmYin3L9dEbEEVWtcq0crRNGJ4/ypFYIssgpyj0DW/XwE3rhTmm1ysnPyBRcI15JFYY+1HcAcIeS+vyCW31KmVAh6Vb53X2aS6yfpL5MTa84rjII9xztkhOVQLfFzimgDP0ITeYSei2YnKt/NzxnVQ38d9rWdRFu1I0aKV8/OD6Nl8eHQNYLlaZTEcgg/LMpnk3eLydeAetABR0C2UNfFMlKi9EU2KH0Oo/UvaqVifvoF8CBeQl0J7PgxS2og6PJpklPmhM+sj/BedD68Gg+txi1oud25bQnAup7cdEZlU2yjzjcVTYGnnVOo+DSF8piunBzQAymjTOkuXGvDQcmAW9g2lQH9EiTb5Qg783wsL6fMqlmWCpktyX7FePUoeCTXd7P7z4qnpmyEQqTS5gLXqcOTPbZnnxhI/VoSHklojMtwbvp/t/3/sCJa48ruxD+SoLF+A3NYXrrsbZmbqYqX2FkWnWRUqqMWzK2yB1E1F2NI52JnKBgfyemizMEeJ2K5V/PuT9P+1sJumnoatWIHj9BRZuGnBCzvdqnk=
