sudo: false
language: node_js
node_js:
- '7'
env:
  global:
  - GH_REF: kamataryo/eslint-snipets
  - secure: dSWe7AHZx9j6rHf/+otu22wOCaRNFoMS7xz+5/flVPVLtUNCvB0Sr8IRtnGqFkqGFzTibB7atxPFvNq1jmHoKWAmZQnhRA/R3/9W4A6tnFILUyTrVdFGkX9vFw5whY5qw7m3lM2K+5jF83Rr49C7DMq4r2gO15y1anCXrEIu7wlLGCFaG7Zw+9CpXSItpUCJCK8H68ffqYsa2XzLDpOHQD0arZ3T3gzXoz6uVoK9/C/QJxTOq0rTiP2LS3e5sZYRoO7MrHyWROa9YiPp5t+lz7W40t7sGoJFSCpI5ZLBh77CRAq8GpEIlnh7DbOlhKO6BvtiL8alB71AubXjk1G0ObqbeCqeym/sM7ksyEOmLeCecNyN+lTL4iKMWgVKjVvkXvfqH63/7Epl/+WONVvFKORkXOJJ/NNbKK8Vi1W4/oXYA/U5ps1EO8W3oo5hybc4zCHWGBW3Ubs4R0rRR3lomcmAW2L80PEj90yk5P8tdHlK88X19SFmUHn+k0/w93rvw+DsYnEx1KDfw/kyv6wCe99T7BDgXRWsRfC+HBAyOiaQh5rl/ktSgovIS3FFXcGhqj9Q1U1YNM/NH1G0GloRrFuqXA8NvkmYKQF9LLvTxPBBP4u+3e5xtVyjR094TVysWxKBE5BtcPe79x3SZ54mTtPDiMk/EzBsDLcVa4HcyrU=
cache:
  yarn: true
  directories:
  - "~/.cache/yarn"
before_script:
- yarn global add npm-check-updates
script:
- node .bin/build.js
after_success:
- .bin/apm-release.sh
